[package]
name = "algorithm_benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
aes = "0.8.2"
block-modes = "0.9.1"
generic-array = "0.14.6"
priority-queue = "1.3.0"

[[bin]]
name = "benchmark"
path = "src/main.rs"
